<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUGSEJ1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUGSEJ1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUGSEJ1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUGSEJ1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUGSEJ1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'UGSEJ1Y',
    'container.build_id' => 'aafb9239',
    'container.build_time' => 1652549304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUGSEJ1Y');
