<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMdXYAOQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMdXYAOQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMdXYAOQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMdXYAOQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMdXYAOQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MdXYAOQ',
    'container.build_id' => 'ae657300',
    'container.build_time' => 1650572852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMdXYAOQ');
