<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFdfj9qO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFdfj9qO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFdfj9qO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFdfj9qO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFdfj9qO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fdfj9qO',
    'container.build_id' => '32dd0826',
    'container.build_time' => 1651183081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFdfj9qO');
